language: python
cache: pip
matrix:
    include:
        - os: linux
          sudo: required
          python: 3.4
          env: GDELT=py34
        - os: linux
          sudo: required
          python: 3.5
          env: GDELT=py35
        - os: linux
          sudo: required
          python: 3.6
          env: GDELT=py36
        - os: osx
          language: generic
          env: GDELT=py34
        - os: osx
          language: generic
          env: GDELT=py35
        - os: osx
          language: generic
          env: GDELT=py36

install:
    - which python
    - python --version
    - "pip install numpy; pip install scipy; pip install pandas"
    - source travis/install.sh
    - which python
    - python --version
    - 'pip install pip -U'
    - "pip install pytest-cov"
    - "python setup.py install"
script:
  - py.test --cov=./

cache:
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

after_success:
  - codecov
